Try 101

diff --git a/.github/workflows/tf_Indev_1Onpush_008Doecho_2Bydevplanapply2.yml b/.github/workflows/tf_Indev_1Onpush_008Doecho_2Bydevplanapply2.yml
--- a/.github/workflows/tf_Indev_1Onpush_008Doecho_2Bydevplanapply2.yml
+++ b/.github/workflows/tf_Indev_1Onpush_008Doecho_2Bydevplanapply2.yml
@@ -40,7 +40,7 @@ jobs:
 
     # Log into Azure with OIDC integration if branch is main
     - name: 'Az CLI login for Main branch' 
-      if: github.ref == 'refs/heads/main'
+      # if: github.ref == 'refs/heads/main'
       uses: azure/login@v1
       with:
         client-id: ${{ secrets.AZURE_DEV_CLIENT_ID }}
@@ -50,7 +50,7 @@ jobs:
     # Run Terraform init for Main branch
     - name: Terraform Init for Main branch
       id: init-main
-      if: github.ref == 'refs/heads/main'
+      # if: github.ref == 'refs/heads/main'
       env:
         STORAGE_ACCOUNT: ${{ secrets.STATE_DEV_STORAGE_ACCOUNT_NAME }}
         CONTAINER_NAME: ${{ secrets.STATE_DEV_CONTAINER_NAME }}
@@ -62,7 +62,7 @@ jobs:
 
     # Run Terraform apply if branch is main
     - name: Terraform Apply for Main branch
-      if: github.ref == 'refs/heads/main'
+      # if: github.ref == 'refs/heads/main'
       id: apply
       env:
         ARM_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
@@ -73,19 +73,19 @@ jobs:
     # Run formatting and validate if the branch is not main
     - name: Terraform Init for other branches
       id: init
-      if: github.ref != 'refs/heads/main'
+      # if: github.ref != 'refs/heads/main'
       run: terraform init -backend=false
 
     # Run a Terraform format
     - name: Terraform format for other branches
-      if: github.ref != 'refs/heads/main'
+      # if: github.ref != 'refs/heads/main'
       id: fmt
       run: terraform fmt -check
 
     # Run a Terraform validate
     - name: Terraform validate for other branches
       id: validate
-      if: (success() || failure()) && github.ref != 'refs/heads/main'
+      # if: (success() || failure()) && github.ref != 'refs/heads/main'
       env:
         ARM_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
